language: r
sudo: required
warnings_are_errors: false

r_binary_packages:
  - reshape2
  - ggplot2
  - jsonlite
  - Rcpp
  - gtools
  - markdown
  - knitr
  - xts
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

notifications:
  email:
  on_success: change
  on_failure: change
