# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: c

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_github jgabry/shinyBS@shinyBS_for_shinyStan 
  - ./travis-tool.sh install_github bwlewis/rthreejs
  - ./travis-tool.sh install_github rstudio/shinyapps
  - ./travis-tool.sh install_deps

script: 
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - BOOTSTRAP_LATEX=1
  - _R_CHECK_FORCE_SUGGESTS_=0

notifications:
  email:
    recipients:
      - jgabry@gmail.com
    on_success: change
    on_failure: change