language: r

sudo: required

warnings_are_errors: true

r_github_packages:
  - rstudio/shinyapps

notifications:
  email:
    recipients:
      - jgabry@gmail.com
    on_success: change
    on_failure: change