language: r

warnings_are_errors: true

r_github_packages:
 - bwlewis/rthreejs
 - ebailey78/shinyBS@shinyBS3 

after_failure:
  - ./travis-tool.sh dump_logs
  
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
    
notifications:
  email:
    recipients:
      - jgabry@gmail.com
    on_success: change
    on_failure: change
