language: r
sudo: required

cran: http://cran.rstudio.com/
r_check_revdep: false
pandoc: false

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

r_binary_packages:
  - coda
  - dygraphs
  - ggplot2
  - gtools
  - httpuv
  - inline
  - jsonlite
  - knitr
  - markdown
  - reshape2
  - Rcpp
  - RUnit
  - shiny
  - testthat
  - xts
  - yaml

notifications:
  email:
  on_success: change
  on_failure: change
