language: r

sudo: required

r_check_force_suggests: false
warnings_are_errors: false

r_github_packages:
  - rstudio/shinyapps
  - stan-dev/rstan@develop/rstan/rstan

notifications:
  email:
    recipients:
      - jgabry@gmail.com
    on_success: change
    on_failure: change