language: r
r: devel
cache: packages

r_github_packages:
  - HenrikBengtsson/matrixStats@develop
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(function_exclusions = c("launch$", "launch_shinystan_demo"), line_exclusions = list("R/zzz.R"))'