language: r
sudo: required

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

r_binary_packages:
  - coda
  - dygraphs
  - ggplot2
  - gtools
  - inline
  - jsonlite
  - knitr
  - markdown
  - Rcpp
  - reshape2
  - shiny
  - testthat
  - xtable
  - xts

notifications:
  email:
  on_success: change
  on_failure: change
