language: r

sudo: required

r_github_packages:
  - stan-dev/rstan@develop/rstan/rstan
  - rstudio/shinyapps

r_check_force_suggests: false
warnings_are_errors: true

notifications:
  email:
    recipients:
      - jgabry@gmail.com
    on_success: change
    on_failure: change